jafarDOB = '12 jan 2012' # string
a = 10 # integer
b = 12.3 # float
c = 'akash' # string
d = True # boolean
e = False # boolean
print(jafarDOB)
print(type(jafarDOB))
print('value of a:',a)
print('type of data in a:',type(a))
print('value of b:',b)
print('type of data in b:',type(b))
f = float(a)
print('value of f:',f)
print('type of f:',type(f))
g = int(b)
print('value of g:',g)
h = float('100')
print('value of h:',h)
print('type of h:',type(h))
i = int(True)
print('value of i:',i)
print('type of i:',type(i))
j = int(False)
print('value of j:',j)
print('type of j:',type(j))
k = bool(0)
print('value of k:',k)
print('type of k:',type(k))
l = bool(1)
print('value of l:',l)
print('type of l:',type(l))
m = bool(2)
print('value of m:',m)
print('type of m:',type(m))
n = bool('')
print('value of n:',n)
print('type of n:',type(n))
o = bool('akash')
print('value of o:',o)
print('type of o:',type(o))